### ISSUE TITLE
pylint does not [offically] support pyproject.toml yet

### ISSUE THREAD

**Issue by laike9m** [flying-sheep/awesome-python-packaging#2]
http://pylint.pycqa.org/en/latest/whatsnew/2.5.html

The support will be added in pylint 2.5, but it has not been released yet.

**Comment by flying-sheep** [comment]
The same now applies to coverage.py. What do you think, should we put like a warning about it being in an unreleased version?

**Comment by hoefling** [comment]
`coverage>=5.0` supports `pyproject.toml` now, also does `setuptools-scm>=3.4`.

**Comment by layday** [comment]
v3.4 of setuptools_scm is not released yet and there a couple of issues left to resolve with `pyproject.toml` integration (see https://github.com/pypa/setuptools_scm/issues/374).

**Comment by layday** [comment]
`setuptools_scm` has added pyproject support in v3.4.1.
