### ISSUE TITLE
Mypy now supports pyproject.toml

### ISSUE THREAD

**Issue by CAM-Gerlach** [flying-sheep/awesome-python-packaging#6]
Mypy now supports pyproject.toml in python/mypy#10219 released with v0.900 (AFAIK, since the PR isn't marked with a milestone), FYI. Aside from pipenv, flake8 is the last listed tool not supporting pyproject.toml.

Also, the formatting between pylint and flake8 looks a little borked.

Happy to submit a PR if desired.

**Comment by flying-sheep** [comment]
Thank you! Indeed it does!
