### ISSUE TITLE
Add pre-commit to the list

### ISSUE THREAD

**Issue by datacycling** [flying-sheep/awesome-python-packaging#7]
Great list, thanks for putting this up. 

One tool to add in the Others category would be pre-commit, sadly this tool does not support pyproject.toml ( https://github.com/pre-commit/pre-commit/issues/1165 )

**Comment by flying-sheep** [comment]
Of course, I’m using that extensively! Thanks!

I think it’s the only tool where I prefer configuration to be elsewhere, as it’s pretty lengthy. The example in that issue is a bad faith argument though. Even without changes to the config structure, this could look much better:

```toml
[[tool.pre-commit.repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v4.0.1"
hooks = [
  {id = "trailing-whitespace"},
  {id = "end-of-file-fixer"},
  {id = "check-docstring-first"},
  {id = "check-json"},
  {id = "check-yaml"},
  {id = "debug-statements"},
  {id = "name-tests-test"},
  {id = "double-quote-string-fixer"},
]

[[tool.pre-commit.repos]]
repo = "https://github.com/PyCQA/flake8"
rev = "3.9.2"
hooks = [
 {id = "flake8", additional_dependencies = [
    "flake8-typing-imports==1.10.0",
 ]},
]

...

[[tool.pre-commit.repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v2.16.0"
hooks = [
  {id = "pyupgrade", args = ["--py36-plus"]},
]

...
```
